defmodule Craftweg.Blog.Post do
  @moduledoc """
  This module is a struct that represents a blog post.
  """

  defstruct [:path, :slug, :title, :excerpt, :date, :categories, :body]

  @doc """
  This method takes the absolute path to the file representing a blog post,
  the contents of the file, and the attributes that have been generated by
  the parser and returns an instance of the Craftweg.Blog.Post struct.
  """
  @spec build(
          binary
          | maybe_improper_list(
              binary | maybe_improper_list(any, binary | []) | char,
              binary | []
            ),
          any,
          any
        ) :: Craftweg.Blog.Post
  def build(path, _attrs, body) do
    filename_without_extension = path |> Path.rootname() |> Path.split() |> Enum.take(-1) |> hd
    [year, month, day] = filename_without_extension |> String.split("-") |> Enum.take(3)
    date = Date.from_iso8601!("#{year}-#{month}-#{day}")
    slug = year <> "/" <> month <> "/" <> day <> "/" <> filename_without_extension

    struct!(
      __MODULE__,
      path: path,
      slug: slug,
      title: filename_without_extension,
      date: date,
      body: body,
      categories: [],
      excerpt: ""
    )
  end
end
