name: website

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: website-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEBUG: 1
  OTP_VERSION: 26.1.2
  ELIXIR_VERSION: 1.15.6
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    services:
      db:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: jdx/mise-action@v2

      - name: Restore Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ hashFiles('mix.lock') }}

      - run: mix deps.get

      - run: mix test
