name: website

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: website-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEBUG: 1
  OTP_VERSION: 25.0.4
  ELIXIR_VERSION: 1.13.4
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    services:
      db:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Restore Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}

      - run: mix deps.get

      - run: mix test
